language: node_js


node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - "node"

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  # install dependencies and check that Cypress can run
  override:
    - npm ci
    - npm run cy:verify

script:
  # start server in the background
  - npm run start:ci &
  # run all Cypress tests and record on the dashboard
  - npm run cy:run -- --record --key b602b4d5-1d12-4b54-a76a-09c920fe5087
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true